# Generated by Django 2.2.5 on 2019-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=70)),
                ('first_name', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=200)),
                ('checkbox', models.BooleanField()),
            ],
        ),
    ]
